-- 2023-04-05-06 본사 인트라넷 SQL 스터디
-- 1. ADMIN > 마스터관리 > 고객사관리
-- 테이블
SELECT * FROM CUSTOMERS_NAME;

SELECT C_NAME_CD
		, C_NAME
FROM CUSTOMERS_NAME 
WHERE 1=1
-- AND C_NAME LIKE '%'||#{searchName}||'%'
ORDER BY C_NAME_CD DESC
; -- 38 rows : 화면과 로우 수, 정렬 순서 일치

-- 2. ADMIN > 마스터관리 > 권한관리 > 공통코드 관리
-- 테이블
SELECT * FROM COMMON_CODE;

SELECT MAJOR_CODE 
		, MINOR_CODE 
		, NAME1
		, NAME2
		, KEY01
		, KEY02
		, KEY03
		, KEY04
		, KEY05
		, KEY06
		, KEY07
		, KEY08
		, KEY09
		, KEY10
		, SORT_NO 
		, DESCR
		, TO_CHAR(INSERT_DATE, 'YYYY/MM/DD') INSERT_DATE
		, TO_CHAR(UPDATE_DATE, 'YYYY/MM/DD') UPDATE_DATE
		, USE_FG
FROM COMMON_CODE
WHERE 1=1
AND MAJOR_CODE = '**'
ORDER BY MAJOR_CODE, MINOR_CODE
; -- 84 rows : 화면과 로우 수, 정렬 순서 일치

-- 3. ADMIN > 마스터관리 > 권한관리 > 메뉴/프로그램 관리
-- 테이블
SELECT * FROM CM_MS_MENU ORDER BY MENU_ID;

SELECT MENU_ID
		, MENU_NM
		, CONCAT(LPAD(' ', (MENU_LVL-1)*4), MENU_NM) MENU_NM_VIEW
		, MENU_LVL
		, UP_MENU_ID
		, MENU_TYPE
		, DISP_ORD
		, USE_YN
FROM CM_MS_MENU 
WHERE 1=1
AND MENU_ID <> '0'
START WITH MENU_ID = '0'
CONNECT BY PRIOR MENU_ID = UP_MENU_ID
ORDER SIBLINGS BY MENU_LVL, DISP_ORD
; -- 252 rows


-- 4. ADMIN > 마스터관리 > 권한관리 > 프로그램 관리
-- 테이블
SELECT * FROM COMMON_CODE;
SELECT * FROM CM_MS_PGM;

SELECT PGM_ID 
		, (
			SELECT NAME1
			FROM COMMON_CODE 
			WHERE 1=1
			AND MINOR_CODE = CMP.BIZ_DET_SP 
			AND ROWNUM = 1
		  ) BIZ_DET_NAME
		, PGM_NM
		, PGM_URL
		, USE_YN
		, BIZ_SP
		, USE_LOG_GEN_YN
		, REG_USER_ID
		, REG_DTTM
		, MOD_USER_ID
		, MOD_DTTM
		, MENU_YN
FROM CM_MS_PGM CMP
ORDER BY CMP.PGM_ID 
; -- 1152 rows : 화면과 로우 수, 정렬 순서 일치

-- 5. ADMIN > 마스터관리 > 권한관리 > 역할별 사용자 관리
-- 테이블
SELECT * FROM TBJIKGUB;

SELECT JIKGUB_NO
		, JIKGUB_NM
FROM TBJIKGUB
WHERE 1=1
--AND JIKGUB_NO LIKE '%'||#{searchId}||'%'
--AND JIKGUB_NO LIKE '%'||#{searchName}||'%'
ORDER BY JIKGUB_NO 
; -- 19 rows


-- 6. ADMIN > 마스터관리 > 권한관리 > 권한관리-역할별 
-- 테이블
SELECT * FROM TBJIKGUB;
SELECT * FROM COMMON_CODE;
SELECT * FROM CM_MS_PGM;
SELECT * FROM CM_TR_ROLE_PGM_AUTH;


SELECT JIKGUB_NO 
		, JIKGUB_NM 
FROM TBJIKGUB 
ORDER BY JIKGUB_NO 
; -- 19 rows

SELECT CMP.PGM_ID
		, CMP.PGM_NM 
		, CMP.PGM_URL 
		, (SELECT NAME1
		   FROM COMMON_CODE CC2
		   WHERE 1=1
		   AND CC2.MINOR_CODE = CMP.BIZ_SP
		   AND CC2.MAJOR_CODE = SUBSTR(CMP.BIZ_SP, 0, 2)) BIZ_NAME
		, (SELECT NAME1 
		   FROM COMMON_CODE CC1
		   WHERE 1=1 
		   AND CC1.MINOR_CODE = CMP.BIZ_DET_SP) BIZ_DET_NAME		
FROM CM_MS_PGM CMP
LEFT JOIN CM_TR_ROLE_PGM_AUTH CTRPA
ON CMP.PGM_ID = CTRPA.PGM_ID
WHERE 1=1
--AND CTRPA.ROLE_ID = #{searchRoleId}
AND CTRPA.ROLE_ID = 0000
ORDER BY CMP.PGM_ID 
;  -- 728 rows


-- 7. ADMIN > 마스터관리 > 권한관리 > 권한관리-사용자별 
-- 테이블
SELECT * FROM TBINSA;
SELECT * FROM COMMON_CODE;
SELECT * FROM CM_MS_PGM;
SELECT * FROM CM_TR_USER_PGM_AUTH;

SELECT INSA_NO 
		, USER_NAME
FROM TBINSA
WHERE 1=1
AND TEAM_CD <> 'ZA'
ORDER BY INSA_NO
; -- 151 rows

SELECT  CTUPA.INSA_NO 
		, CTUPA.PGM_ID
		, CMP.PGM_NM 
		, (SELECT NAME1
		   FROM COMMON_CODE
		   WHERE 1=1
		   AND MINOR_CODE = CMP.BIZ_SP
		   AND MAJOR_CODE = SUBSTR(CMP.BIZ_SP, 0, 2)) BIZ_NAME
		, CTUPA.USE_START_DT
		, CTUPA.USE_END_DT
FROM CM_MS_PGM CMP 
INNER JOIN CM_TR_USER_PGM_AUTH CTUPA
ON CTUPA.PGM_ID = CMP.PGM_ID 
AND CTUPA.INSA_NO = '99999999' -- #{seacrhInsaNo}
WHERE 1=1
ORDER BY CMP.PGM_ID 
; -- 1016 rows


-- 8. ADMIN > 마스터관리 > 공통관리 > 시스템 메시지 관리 
-- 테이블
SELECT * FROM COM_MESSAGESOURCE WHERE CODE LIKE 'a.a%';

SELECT CODE
		, SUBSTR(CODE, 1, INSTR(CODE, '.', 1, 2)-1) DEPT
		, SUBSTR(CODE, INSTR(CODE, '.', 1, 2)+1, INSTR(CODE, '.', 1, 3)-INSTR(CODE, '.', 1, 2)-1) MTYPE
		, SUBSTR(CODE, INSTR(CODE, '.', 1, 3)+1) MCODE
		, MSG
		, CREATE_NAME 
		, CREATE_DT
FROM COM_MESSAGESOURCE
--WHERE CODE LIKE 'a.a%'
ORDER BY DEPT, MTYPE, MCODE
; -- 414 rows : 화면과 로우 수, 정렬 순서 일치


-- 9. ADMIN > 마스터관리 > 공통관리 > 비밀번호 초기화 관리
-- 테이블
SELECT * FROM TBINSA;
SELECT * FROM TBJIKGUB;
SELECT * FROM TBTEAM;
SELECT * FROM CM_MS_DEPT;
SELECT * FROM CM_TR_DEPT_INSA;

SELECT TI.INSA_NO 
		, TI.USER_NAME 
		, TJ.JIKGUB_NM 
		, TT.TEAM_NM 
		, TI.HAND_PHONE1 || '-' || TI.HAND_PHONE2 || '-' || TI.HAND_PHONE3 HANDPHONE
		, TI.EMAIL 
FROM TBINSA TI
INNER JOIN TBJIKGUB TJ
ON TI.JIKGUB_NO = TJ.JIKGUB_NO 
INNER JOIN TBTEAM TT 
ON TI.TEAM_CD = TT.TEAM_CD 
INNER JOIN CM_TR_DEPT_INSA CTDI
ON TI.INSA_NO = CTDI.INSA_NO 
INNER JOIN CM_MS_DEPT CMD 
ON CTDI.DEPT_ID = CMD.DEPT_ID 
WHERE 1=1
AND TT.TEAM_CD <> 'ZA'
ORDER BY TI.USER_NAME, CMD.DEPT_ID, TT.TEAM_CD, TJ.JIKGUB_NO, TI.INSA_NO -- 참조  
; -- 152 rows


-- 10. ADMIN > 마스터관리 > 사용자메뉴접근정보 > 기간별 접근 정보
-- 테이블
SELECT * FROM COMMON_CODE;
SELECT * FROM CM_LG_PGM_USE_LOG;
SELECT * FROM CM_MS_PGM;
-- 기간별 접근정보 조회

SELECT 	CLPUL_T.DENSE_RANK 
	, CMP.PGM_ID 
	, CMP.PGM_NM
	, (SELECT NAME1
	   FROM COMMON_CODE 
	   WHERE 1=1
	   AND MAJOR_CODE = SUBSTR(CMP.BIZ_SP, 0, 2)
	   AND MINOR_CODE = CMP.BIZ_SP) BIZ_NAME
	, (SELECT NAME1
	   FROM COMMON_CODE
	   WHERE 1=1
	   AND MINOR_CODE = CMP.BIZ_DET_SP) BIZ_DEPT_NAME 
	, CLPUL_T.CNT
FROM CM_MS_PGM CMP
INNER JOIN (
			SELECT PGM_ID
				 , CNT
				 , DENSE_RANK() OVER (ORDER BY CNT DESC) DENSE_RANK
			FROM (
					SELECT PGM_ID 
					, COUNT(PGM_ID) CNT
					FROM CM_LG_PGM_USE_LOG CLPUL
					WHERE REG_DTTM > SYSDATE-7 -- 기본값
					GROUP BY PGM_ID 
				 ) TEMP
		   ) CLPUL_T
ON CMP.PGM_ID = CLPUL_T.PGM_ID
WHERE 1=1
ORDER BY 1, 5
; -- 11 rows : 화면과 로우 수 일치

SELECT * FROM CM_MS_DEPT;
-- 조직정보 조회

SELECT DEPT_ID 
		, UP_DEPT_ID 
		, CASE WHEN DEPT_LVL = 4 THEN '-' || DEPT_NM ELSE DEPT_NM END DEPT_NM
		, DEPT_LVL
		, DEPT_BIZ_CD 
		, DEPT_TYPE
		, DISP_ORD
		, USE_YN
FROM CM_MS_DEPT CMD
WHERE USE_YN = 'Y' -- 참조
AND DEPT_BIZ_CD <> 'ETC' -- 참조
AND DEPT_TYPE IS NOT NULL
START WITH DEPT_ID = '0'
CONNECT BY PRIOR DEPT_ID = UP_DEPT_ID 
; -- 10 rows : 화면과 로우 수, 정렬 순서 일치

SELECT * FROM COMMON_CODE WHERE 1=1 AND MAJOR_CODE LIKE '%SCR%';
-- 화면구분정보 조회

SELECT MAJOR_CODE 
		, MINOR_CODE 
		, NAME1 
		, DESCR
		, USE_FG 
		, SORT_NO
FROM COMMON_CODE 
WHERE 1=1
AND MAJOR_CODE = 'SCR'
ORDER BY MAJOR_CODE, SORT_NO -- 참조
; -- 3 rows : 화면과 로우 수, 정렬 순서 일치

-- 11. ADMIN > 마스터관리 > 사용자메뉴접근정보 > 조직별 접근 정보
-- 테이블
SELECT * FROM TBINSA;
SELECT * FROM TBJIKGUB;
SELECT * FROM TBTEAM;
SELECT * FROM CM_MS_DEPT;
SELECT * FROM CM_MS_PGM;
SELECT * FROM CM_TR_DEPT_INSA;
SELECT * FROM CM_LG_PGM_USE_LOG;
-- 조직별 접근정보 조회

WITH DEPT_LIST AS ( -- 참조
	SELECT TI.INSA_NO
			, TI.USER_ID
			, TI.USER_NAME 
			, TG.JIKGUB_NO
			, TG.JIKGUB_NM 
			, TT.TEAM_CD
			, TT.TEAM_NM 
			, DEPT.DEPT_ID
	FROM TBINSA TI
	INNER JOIN TBJIKGUB TG 
	ON TI.JIKGUB_NO = TG.JIKGUB_NO 
	INNER JOIN TBTEAM TT 
	ON TI.TEAM_CD = TT.TEAM_CD 
	INNER JOIN (
			    SELECT TEMP.DEPT_ID, TEMP.DEPT_TYPE INSA_NO
	            FROM (SELECT CMD.DEPT_ID
	                         , CMD.UP_DEPT_ID
	                         , CMD.DEPT_TYPE
	                  FROM CM_MS_DEPT CMD
	                  WHERE CMD.USE_YN = 'Y'
	                  UNION ALL
	                  SELECT TO_CHAR(CTDI.DEPT_ID || '0' + CTDI.DISP_ORD) DEPT_ID
	                         , CTDI.DEPT_ID AS UP_DEPT_ID
	                         , TO_CHAR(CTDI.INSA_NO) AS DEPT_TYPE
	                  FROM CM_TR_DEPT_INSA CTDI
	                  ) TEMP
			            -- START WITH A.DEPT_ID = #{deptId}
				START WITH TEMP.DEPT_ID = '0'
	            CONNECT BY PRIOR TEMP.DEPT_ID = TEMP.UP_DEPT_ID
			) DEPT
	ON TO_CHAR(TI.INSA_NO) = DEPT.INSA_NO
     AND TI.INSA_NO != 99999999
     AND LENGTH(DEPT.INSA_NO)>= 9
     )
SELECT DL.TEAM_NM
		, DL.JIKGUB_NM
		, DL.USER_NAME
		, CL.PGM_ID 
		, ( SELECT CMP.PGM_NM
		  FROM CM_MS_PGM CMP
		  WHERE CMP.PGM_ID = CL.PGM_ID ) PGM_NM
		, COUNT(CL.USER_ID) CNT
		, MAX(CL.REG_DTTM) LATEST
FROM CM_LG_PGM_USE_LOG CL
INNER JOIN DEPT_LIST DL
ON CL.USER_ID = DL.USER_ID
GROUP BY CL.USER_ID, DL.TEAM_NM, DL.JIKGUB_NO, DL.JIKGUB_NM, DL.USER_NAME, CL.PGM_ID -- 참조
ORDER BY DL.JIKGUB_NO, DL.USER_NAME, COUNT(1) DESC -- 참조
; -- 1176 rows : 화면과 로우 수 일치
  
SELECT * FROM CM_MS_DEPT;
SELECT * FROM CM_TR_DEPT_INSA;
-- 인사조직 리스트 조회

SELECT CMD.DEPT_ID 
		, CMD.UP_DEPT_ID 
		, CMD.DEPT_NM 
		, CMD.DEPT_LVL 
		, CRDI.INSA_NO
		, TI.USER_NAME 
FROM CM_MS_DEPT CMD
LEFT JOIN CM_TR_DEPT_INSA CRDI 
ON CMD.DEPT_ID = CRDI.DEPT_ID 
LEFT JOIN TBINSA TI 
ON CRDI.INSA_NO = TI.INSA_NO 
AND CMD.USE_YN = 'Y'
AND NVL(TI.TEAM_CD, 'X') NOT IN ('ZA', 'SB', 'FF') -- 참조
AND TI.INSA_NO NOT IN ('99999999', '88888888') -- 참조
START WITH CMD.DEPT_ID = '0'
CONNECT BY PRIOR CMD.DEPT_ID = CMD.UP_DEPT_ID
ORDER SIBLINGS BY CMD.DEPT_LVL, CMD.DISP_ORD -- 참조
; -- 1075 rows


-- 12. ADMIN > 마스터관리 > 사용자메뉴접근정보 > 사용자별 접근 정보
-- 테이블
SELECT * FROM TBINSA;

SELECT TI.INSA_NO
		, TI.USER_NAME
FROM TBINSA TI
WHERE 1=1
AND TI.TEAM_CD <> 'ZA'
ORDER BY TI.INSA_NO
; -- 151 rows

SELECT * FROM CM_LG_PGM_USE_LOG;	
SELECT * FROM CM_MS_PGM;	
SELECT * FROM TBINSA;	 

SELECT CL.REG_DTTM 
	, CMP.PGM_ID 
	, CMP.PGM_NM 
	, (SELECT NAME1 FROM COMMON_CODE WHERE 1=1 AND MAJOR_CODE = SUBSTR(CMP.BIZ_SP, 0, 2) AND MINOR_CODE = CMP.BIZ_SP) BIZ_NAME
	, (SELECT NAME1 FROM COMMON_CODE WHERE 1=1 AND MINOR_CODE = CMP.BIZ_DET_SP) BIZ_DET_NAME
FROM CM_LG_PGM_USE_LOG CL
INNER JOIN CM_MS_PGM CMP 
ON CL.PGM_ID = CMP.PGM_ID 
INNER JOIN TBINSA TI 
ON CL.USER_ID = TI.USER_ID 
WHERE 1=1
AND TI.INSA_NO = '88888888' -- #{searchInsaNo} 
ORDER BY 1 DESC
; -- 60 rows : 화면과 로우 수, 정렬 순서 일치





















